DATA SEGMENT
    ARRAY   DB 00H,02H,01H,04H
    RESULT  DB ?
DATA ENDS
CODE SEGMENT
    ASSUME CS:CODE,DS:DATA
    START:
    MOV AX,DATA
    MOV DS,AX
    LEA SI,ARRAY
    MOV CX,3
    MOV AL,[SI]
SUM:

    INC SI
    ADD AL,[SI]
    MOV RESULT,AL
    LOOP SUM
CODE ENDS
END START   