DATA SEGMENT
    SARRAY       DW   0AH,09H,33H,20H,03H,11H,56H,93H,05H,08H
    DARRAY       DW   10DUP(0)
DATA ENDS

CODE SEGMENT
    ASSUME CS:CODE,DS:DATA
    START:
    MOV AX,DATA
    MOV DS,AX
        
    MOV AX,00
    MOV SI,00
    MOV DI,00
    MOV CX,10

NEXT:
    MOV AX,SARRAY[SI]
    MOV DARRAY[DI],AX
    INC SI
    INC DI
    LOOP NEXT
       
CODE ENDS
END START
    